# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saul/proj/Fondue-Rays/Fondue-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saul/proj/Fondue-Rays/Fondue-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-bin\" \"assimp-dev\" \"libassimp4.0.1-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saul/proj/Fondue-Rays/Fondue-core/CMakeFiles /home/saul/proj/Fondue-Rays/Fondue-core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saul/proj/Fondue-Rays/Fondue-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Fondue-Rays

# Build rule for target.
Fondue-Rays: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Fondue-Rays
.PHONY : Fondue-Rays

# fast build rule for target.
Fondue-Rays/fast:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/build
.PHONY : Fondue-Rays/fast

#=============================================================================
# Target rules for targets named GLAD

# Build rule for target.
GLAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GLAD
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f Dependencies/glfw-3.2.1/CMakeFiles/uninstall.dir/build.make Dependencies/glfw-3.2.1/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f Dependencies/glfw-3.2.1/src/CMakeFiles/glfw.dir/build.make Dependencies/glfw-3.2.1/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/contrib/irrXML/CMakeFiles/IrrXML.dir/build.make Dependencies/assimp-4.0.1/contrib/irrXML/CMakeFiles/IrrXML.dir/build
.PHONY : IrrXML/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/code/CMakeFiles/assimp.dir/build.make Dependencies/assimp-4.0.1/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named assimp_cmd

# Build rule for target.
assimp_cmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp_cmd
.PHONY : assimp_cmd

# fast build rule for target.
assimp_cmd/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build.make Dependencies/assimp-4.0.1/tools/assimp_cmd/CMakeFiles/assimp_cmd.dir/build
.PHONY : assimp_cmd/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousSubmit.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousMemCheck.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousConfigure.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalSubmit.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalMemCheck.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalTest.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyUpdate.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyStart.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyMemoryCheck.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyBuild.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalUpdate.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/unit.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/unit.dir/build
.PHONY : unit/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousBuild.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/Continuous.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/Experimental.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalConfigure.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyTest.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyCoverage.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalCoverage.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyMemCheck.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousStart.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlySubmit.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousCoverage.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/Nightly.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyConfigure.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalStart.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousTest.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousUpdate.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalBuild.dir/build.make Dependencies/assimp-4.0.1/test/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

interfaces/raymarch.o: interfaces/raymarch.cpp.o

.PHONY : interfaces/raymarch.o

# target to build an object file
interfaces/raymarch.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/interfaces/raymarch.cpp.o
.PHONY : interfaces/raymarch.cpp.o

interfaces/raymarch.i: interfaces/raymarch.cpp.i

.PHONY : interfaces/raymarch.i

# target to preprocess a source file
interfaces/raymarch.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/interfaces/raymarch.cpp.i
.PHONY : interfaces/raymarch.cpp.i

interfaces/raymarch.s: interfaces/raymarch.cpp.s

.PHONY : interfaces/raymarch.s

# target to generate assembly for a file
interfaces/raymarch.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/interfaces/raymarch.cpp.s
.PHONY : interfaces/raymarch.cpp.s

src/glad.o: src/glad.c.o

.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i

.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s

.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/graphics/3d/batches/textured.o: src/graphics/3d/batches/textured.cpp.o

.PHONY : src/graphics/3d/batches/textured.o

# target to build an object file
src/graphics/3d/batches/textured.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/batches/textured.cpp.o
.PHONY : src/graphics/3d/batches/textured.cpp.o

src/graphics/3d/batches/textured.i: src/graphics/3d/batches/textured.cpp.i

.PHONY : src/graphics/3d/batches/textured.i

# target to preprocess a source file
src/graphics/3d/batches/textured.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/batches/textured.cpp.i
.PHONY : src/graphics/3d/batches/textured.cpp.i

src/graphics/3d/batches/textured.s: src/graphics/3d/batches/textured.cpp.s

.PHONY : src/graphics/3d/batches/textured.s

# target to generate assembly for a file
src/graphics/3d/batches/textured.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/batches/textured.cpp.s
.PHONY : src/graphics/3d/batches/textured.cpp.s

src/graphics/3d/rasterizables/model.o: src/graphics/3d/rasterizables/model.cpp.o

.PHONY : src/graphics/3d/rasterizables/model.o

# target to build an object file
src/graphics/3d/rasterizables/model.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/rasterizables/model.cpp.o
.PHONY : src/graphics/3d/rasterizables/model.cpp.o

src/graphics/3d/rasterizables/model.i: src/graphics/3d/rasterizables/model.cpp.i

.PHONY : src/graphics/3d/rasterizables/model.i

# target to preprocess a source file
src/graphics/3d/rasterizables/model.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/rasterizables/model.cpp.i
.PHONY : src/graphics/3d/rasterizables/model.cpp.i

src/graphics/3d/rasterizables/model.s: src/graphics/3d/rasterizables/model.cpp.s

.PHONY : src/graphics/3d/rasterizables/model.s

# target to generate assembly for a file
src/graphics/3d/rasterizables/model.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/rasterizables/model.cpp.s
.PHONY : src/graphics/3d/rasterizables/model.cpp.s

src/graphics/3d/scenes/camera.o: src/graphics/3d/scenes/camera.cpp.o

.PHONY : src/graphics/3d/scenes/camera.o

# target to build an object file
src/graphics/3d/scenes/camera.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/scenes/camera.cpp.o
.PHONY : src/graphics/3d/scenes/camera.cpp.o

src/graphics/3d/scenes/camera.i: src/graphics/3d/scenes/camera.cpp.i

.PHONY : src/graphics/3d/scenes/camera.i

# target to preprocess a source file
src/graphics/3d/scenes/camera.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/scenes/camera.cpp.i
.PHONY : src/graphics/3d/scenes/camera.cpp.i

src/graphics/3d/scenes/camera.s: src/graphics/3d/scenes/camera.cpp.s

.PHONY : src/graphics/3d/scenes/camera.s

# target to generate assembly for a file
src/graphics/3d/scenes/camera.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/3d/scenes/camera.cpp.s
.PHONY : src/graphics/3d/scenes/camera.cpp.s

src/graphics/glwrappers/buffer.o: src/graphics/glwrappers/buffer.cpp.o

.PHONY : src/graphics/glwrappers/buffer.o

# target to build an object file
src/graphics/glwrappers/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/buffer.cpp.o
.PHONY : src/graphics/glwrappers/buffer.cpp.o

src/graphics/glwrappers/buffer.i: src/graphics/glwrappers/buffer.cpp.i

.PHONY : src/graphics/glwrappers/buffer.i

# target to preprocess a source file
src/graphics/glwrappers/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/buffer.cpp.i
.PHONY : src/graphics/glwrappers/buffer.cpp.i

src/graphics/glwrappers/buffer.s: src/graphics/glwrappers/buffer.cpp.s

.PHONY : src/graphics/glwrappers/buffer.s

# target to generate assembly for a file
src/graphics/glwrappers/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/buffer.cpp.s
.PHONY : src/graphics/glwrappers/buffer.cpp.s

src/graphics/glwrappers/cubemap.o: src/graphics/glwrappers/cubemap.cpp.o

.PHONY : src/graphics/glwrappers/cubemap.o

# target to build an object file
src/graphics/glwrappers/cubemap.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/cubemap.cpp.o
.PHONY : src/graphics/glwrappers/cubemap.cpp.o

src/graphics/glwrappers/cubemap.i: src/graphics/glwrappers/cubemap.cpp.i

.PHONY : src/graphics/glwrappers/cubemap.i

# target to preprocess a source file
src/graphics/glwrappers/cubemap.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/cubemap.cpp.i
.PHONY : src/graphics/glwrappers/cubemap.cpp.i

src/graphics/glwrappers/cubemap.s: src/graphics/glwrappers/cubemap.cpp.s

.PHONY : src/graphics/glwrappers/cubemap.s

# target to generate assembly for a file
src/graphics/glwrappers/cubemap.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/cubemap.cpp.s
.PHONY : src/graphics/glwrappers/cubemap.cpp.s

src/graphics/glwrappers/framebuffer.o: src/graphics/glwrappers/framebuffer.cpp.o

.PHONY : src/graphics/glwrappers/framebuffer.o

# target to build an object file
src/graphics/glwrappers/framebuffer.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/framebuffer.cpp.o
.PHONY : src/graphics/glwrappers/framebuffer.cpp.o

src/graphics/glwrappers/framebuffer.i: src/graphics/glwrappers/framebuffer.cpp.i

.PHONY : src/graphics/glwrappers/framebuffer.i

# target to preprocess a source file
src/graphics/glwrappers/framebuffer.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/framebuffer.cpp.i
.PHONY : src/graphics/glwrappers/framebuffer.cpp.i

src/graphics/glwrappers/framebuffer.s: src/graphics/glwrappers/framebuffer.cpp.s

.PHONY : src/graphics/glwrappers/framebuffer.s

# target to generate assembly for a file
src/graphics/glwrappers/framebuffer.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/framebuffer.cpp.s
.PHONY : src/graphics/glwrappers/framebuffer.cpp.s

src/graphics/glwrappers/indexbuffer.o: src/graphics/glwrappers/indexbuffer.cpp.o

.PHONY : src/graphics/glwrappers/indexbuffer.o

# target to build an object file
src/graphics/glwrappers/indexbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/indexbuffer.cpp.o
.PHONY : src/graphics/glwrappers/indexbuffer.cpp.o

src/graphics/glwrappers/indexbuffer.i: src/graphics/glwrappers/indexbuffer.cpp.i

.PHONY : src/graphics/glwrappers/indexbuffer.i

# target to preprocess a source file
src/graphics/glwrappers/indexbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/indexbuffer.cpp.i
.PHONY : src/graphics/glwrappers/indexbuffer.cpp.i

src/graphics/glwrappers/indexbuffer.s: src/graphics/glwrappers/indexbuffer.cpp.s

.PHONY : src/graphics/glwrappers/indexbuffer.s

# target to generate assembly for a file
src/graphics/glwrappers/indexbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/indexbuffer.cpp.s
.PHONY : src/graphics/glwrappers/indexbuffer.cpp.s

src/graphics/glwrappers/texture.o: src/graphics/glwrappers/texture.cpp.o

.PHONY : src/graphics/glwrappers/texture.o

# target to build an object file
src/graphics/glwrappers/texture.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/texture.cpp.o
.PHONY : src/graphics/glwrappers/texture.cpp.o

src/graphics/glwrappers/texture.i: src/graphics/glwrappers/texture.cpp.i

.PHONY : src/graphics/glwrappers/texture.i

# target to preprocess a source file
src/graphics/glwrappers/texture.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/texture.cpp.i
.PHONY : src/graphics/glwrappers/texture.cpp.i

src/graphics/glwrappers/texture.s: src/graphics/glwrappers/texture.cpp.s

.PHONY : src/graphics/glwrappers/texture.s

# target to generate assembly for a file
src/graphics/glwrappers/texture.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/texture.cpp.s
.PHONY : src/graphics/glwrappers/texture.cpp.s

src/graphics/glwrappers/texturearray.o: src/graphics/glwrappers/texturearray.cpp.o

.PHONY : src/graphics/glwrappers/texturearray.o

# target to build an object file
src/graphics/glwrappers/texturearray.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/texturearray.cpp.o
.PHONY : src/graphics/glwrappers/texturearray.cpp.o

src/graphics/glwrappers/texturearray.i: src/graphics/glwrappers/texturearray.cpp.i

.PHONY : src/graphics/glwrappers/texturearray.i

# target to preprocess a source file
src/graphics/glwrappers/texturearray.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/texturearray.cpp.i
.PHONY : src/graphics/glwrappers/texturearray.cpp.i

src/graphics/glwrappers/texturearray.s: src/graphics/glwrappers/texturearray.cpp.s

.PHONY : src/graphics/glwrappers/texturearray.s

# target to generate assembly for a file
src/graphics/glwrappers/texturearray.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/texturearray.cpp.s
.PHONY : src/graphics/glwrappers/texturearray.cpp.s

src/graphics/glwrappers/vertexarray.o: src/graphics/glwrappers/vertexarray.cpp.o

.PHONY : src/graphics/glwrappers/vertexarray.o

# target to build an object file
src/graphics/glwrappers/vertexarray.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/vertexarray.cpp.o
.PHONY : src/graphics/glwrappers/vertexarray.cpp.o

src/graphics/glwrappers/vertexarray.i: src/graphics/glwrappers/vertexarray.cpp.i

.PHONY : src/graphics/glwrappers/vertexarray.i

# target to preprocess a source file
src/graphics/glwrappers/vertexarray.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/vertexarray.cpp.i
.PHONY : src/graphics/glwrappers/vertexarray.cpp.i

src/graphics/glwrappers/vertexarray.s: src/graphics/glwrappers/vertexarray.cpp.s

.PHONY : src/graphics/glwrappers/vertexarray.s

# target to generate assembly for a file
src/graphics/glwrappers/vertexarray.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/glwrappers/vertexarray.cpp.s
.PHONY : src/graphics/glwrappers/vertexarray.cpp.s

src/graphics/window.o: src/graphics/window.cpp.o

.PHONY : src/graphics/window.o

# target to build an object file
src/graphics/window.cpp.o:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/window.cpp.o
.PHONY : src/graphics/window.cpp.o

src/graphics/window.i: src/graphics/window.cpp.i

.PHONY : src/graphics/window.i

# target to preprocess a source file
src/graphics/window.cpp.i:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/window.cpp.i
.PHONY : src/graphics/window.cpp.i

src/graphics/window.s: src/graphics/window.cpp.s

.PHONY : src/graphics/window.s

# target to generate assembly for a file
src/graphics/window.cpp.s:
	$(MAKE) -f CMakeFiles/Fondue-Rays.dir/build.make CMakeFiles/Fondue-Rays.dir/src/graphics/window.cpp.s
.PHONY : src/graphics/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... Fondue-Rays"
	@echo "... GLAD"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... IrrXML"
	@echo "... assimp"
	@echo "... assimp_cmd"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousConfigure"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalTest"
	@echo "... NightlyUpdate"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... unit"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyTest"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... ContinuousCoverage"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalStart"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... interfaces/raymarch.o"
	@echo "... interfaces/raymarch.i"
	@echo "... interfaces/raymarch.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/graphics/3d/batches/textured.o"
	@echo "... src/graphics/3d/batches/textured.i"
	@echo "... src/graphics/3d/batches/textured.s"
	@echo "... src/graphics/3d/rasterizables/model.o"
	@echo "... src/graphics/3d/rasterizables/model.i"
	@echo "... src/graphics/3d/rasterizables/model.s"
	@echo "... src/graphics/3d/scenes/camera.o"
	@echo "... src/graphics/3d/scenes/camera.i"
	@echo "... src/graphics/3d/scenes/camera.s"
	@echo "... src/graphics/glwrappers/buffer.o"
	@echo "... src/graphics/glwrappers/buffer.i"
	@echo "... src/graphics/glwrappers/buffer.s"
	@echo "... src/graphics/glwrappers/cubemap.o"
	@echo "... src/graphics/glwrappers/cubemap.i"
	@echo "... src/graphics/glwrappers/cubemap.s"
	@echo "... src/graphics/glwrappers/framebuffer.o"
	@echo "... src/graphics/glwrappers/framebuffer.i"
	@echo "... src/graphics/glwrappers/framebuffer.s"
	@echo "... src/graphics/glwrappers/indexbuffer.o"
	@echo "... src/graphics/glwrappers/indexbuffer.i"
	@echo "... src/graphics/glwrappers/indexbuffer.s"
	@echo "... src/graphics/glwrappers/texture.o"
	@echo "... src/graphics/glwrappers/texture.i"
	@echo "... src/graphics/glwrappers/texture.s"
	@echo "... src/graphics/glwrappers/texturearray.o"
	@echo "... src/graphics/glwrappers/texturearray.i"
	@echo "... src/graphics/glwrappers/texturearray.s"
	@echo "... src/graphics/glwrappers/vertexarray.o"
	@echo "... src/graphics/glwrappers/vertexarray.i"
	@echo "... src/graphics/glwrappers/vertexarray.s"
	@echo "... src/graphics/window.o"
	@echo "... src/graphics/window.i"
	@echo "... src/graphics/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

